server:
  port: 8085

spring:
  application:
    name: servicio-notificaciones
  datasource:
    url: jdbc:mysql://localhost:3306/inscribeme_notificaciones?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    time-zone: America/Santiago

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring.boot.admin.client:
  url: http://localhost:8090
  username: admin
  password: admin123
